words = [
'Hello World!',
'Purpl3?',
'PLNT',
'What am I doing!?',
'Discord RPC is broken',
'Github',
'Wine-Launcher Top!',
'If u read this u are cool guy!',
't.me/PLNT_YT?',
'Download Discord',
'Discord RPC is cool!',
"I don't like burger king",
"System.out.println('Hello World');",
"std::cout << 'Hello World!';",
'New discord font is bad and its fact',
"Why did i download discord?",
"What's wrong?",
'Glory to Ukraine!',
"What's wrong, Scared?",
'Python',
'Purpl3_YT - My nick in minecraft'
]